config = {
    'execution': None,
    'timeout': None,
    'debug_stop': None,
    'server_connection': None,
    'server_address': None,
    'release': None,
    'browser': None,
    'device': None,
    'username': None,
    'access_key': None,
    'tunnel_id': None,
    'selenium_port': None,
    'mail': None,
    'm_version': None,
    'email_add': None,
    'SCOPES': None,
    'storage_file': None,
    'client_secret': None,
    'q_from': None,
    'q_sub_ssq': None,
    'q_sub_cq': None,
    'q_sub_scq': None,
    'q_sub_baa': None,
    'q_ghi_hcc_sub': None,
    'q_ghi_from': None
}
